### ISSUE TITLE
Milestone #1

### ISSUE THREAD

**Issue by Suzii** [JuroUhlar/PV247-Chat-app#2]
# Status: ✔️ 
Below are just suggestions to consider for the next milestones.

The prototype already contains all the required functionality, job well done. 👍 
I was curious, why you only used some css framework for the login screen and not the chat application itself. I am not saying it is a requirement, but it would have saved you quite a lot of time and would have made the app look more consistent.
 
# Code suggestions
Make all of your typescript interfaces readonly so that the compiler will help you to make sure you treat props state and other objects as immutable.
I would rename `BarItem` component to something more specific (it only renders channels, nothing else).
I hope to see no commented-out code nor console warnings in the final submission 😉

**Comment by JuroUhlar** [comment]
- [x] Make all of typescript interfaces readonly
- [x] Rename BarItem component to something more specific
- [x] Fix warnings in console
- [x] Make app look consistent
