### ISSUE TITLE
Milestone #2

### ISSUE THREAD

**Issue by HanaNavratilova** [JuroUhlar/PV247-Chat-app#3]
**Status:** ✔

Nice, clean code 👍 
⚠️ Do not forget to implement all the functionality mentioned in the assignment :) 

**Code suggestions:**
- Function in `onKeyPress={...}` should be a named function (ChannelEditModal.tsx:83)
- You're not consistent in style of private methods. In channels your methods are in this style `updateChannel = () => {}` while in messages they starts with `_` `_onLike = () => {}`
- In `messageListingReducers` is `messageIds` unnecessary. When you want to add a message into your state, you now have to do it twice. You can get ids from `messages` and save performance using memoization.
```
export const messageListingReducers = combineReducers({
  messages: messagesReducer,
  messageIds: messageIdsReducer,
});
```
**Nitpicking details:**
- You forgot to write an interface for the state in `ChannelBarItem` Component.
- Sometimes, you have unused functions in your code (for example ChannelListing.tsx:50). If you'll use them later, ignore this comment.
- It would be more comprehensible if you split the Message.ts file into Message.ts and MessagePopularity.ts. Similarly in the file usersUtils.ts.

**Comment by JuroUhlar** [comment]
- [x] Function in onKeyPress={...} should be a named function
- [x] You're not consistent in style of private methods.
- [x] In messageListingReducers is messageIds unnecessary.
- [x] You forgot to write an interface for the state in ChannelBarItem Component.
- [x] Sometimes, you have unused functions in your code (for example ChannelListing.tsx:50). If you'll use them later, ignore this comment.
- [x] It would be more comprehensible if you split the Message.ts file into Message.ts and MessagePopularity.ts. Similarly in the file usersUtils.ts.
